# Generated by Django 5.1.5 on 2025-01-20 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
