# Generated by Django 5.1.5 on 2025-01-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_work', 'В работе'), ('completed', 'Завершена')], default='New', max_length=15),
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
